<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <RootNamespace>BF2Presence</RootNamespace>
    <AssemblyName>BF2Presence</AssemblyName>
    <Version>0.1.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="offsets.json" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Assets\background.jpg" LogicalName="background.jpg" />
    <EmbeddedResource Include="Assets\app.ico" LogicalName="app.ico" />
    <EmbeddedResource Include="Assets\github.png" LogicalName="github.png" />
    <EmbeddedResource Include="offsets.json" LogicalName="offsets.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BF2Presence.Tests" />
  </ItemGroup>

</Project>
